// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM-0NdBKOys5FyHXWQ0PHTbXC6ct18fgo',
    appId: '1:993530648:web:34ae181c25b5672fa2046d',
    messagingSenderId: '993530648',
    projectId: 'coach-app-govarohub',
    authDomain: 'coach-app-govarohub.firebaseapp.com',
    storageBucket: 'coach-app-govarohub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVRfSG7tbk82_vLfpAPqkfm_4UITNmYSE',
    appId: '1:993530648:android:4bdf721a2b63fe92a2046d',
    messagingSenderId: '993530648',
    projectId: 'coach-app-govarohub',
    storageBucket: 'coach-app-govarohub.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgj85wLCDg0fZigAO_SVpGKBZctGfLvh8',
    appId: '1:993530648:ios:ab7373dd301d56f9a2046d',
    messagingSenderId: '993530648',
    projectId: 'coach-app-govarohub',
    storageBucket: 'coach-app-govarohub.firebasestorage.app',
    iosClientId: '993530648-j3snjt18s2103t4259ak5c4d6qsdj37r.apps.googleusercontent.com',
    iosBundleId: 'com.example.coachAppMobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgj85wLCDg0fZigAO_SVpGKBZctGfLvh8',
    appId: '1:993530648:ios:ab7373dd301d56f9a2046d',
    messagingSenderId: '993530648',
    projectId: 'coach-app-govarohub',
    storageBucket: 'coach-app-govarohub.firebasestorage.app',
    iosClientId: '993530648-j3snjt18s2103t4259ak5c4d6qsdj37r.apps.googleusercontent.com',
    iosBundleId: 'com.example.coachAppMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM-0NdBKOys5FyHXWQ0PHTbXC6ct18fgo',
    appId: '1:993530648:web:daef7aeb4197db03a2046d',
    messagingSenderId: '993530648',
    projectId: 'coach-app-govarohub',
    authDomain: 'coach-app-govarohub.firebaseapp.com',
    storageBucket: 'coach-app-govarohub.firebasestorage.app',
  );
}
